//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public long company_id { get; set; }
        public string company_code { get; set; }
        public string company_short_name { get; set; }
        public string company_name { get; set; }
        public Nullable<long> company_parent_id { get; set; }
        public Nullable<bool> is_branch { get; set; }
        public Nullable<bool> enabled { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string update_user { get; set; }
    }
}
