//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.transaction_master = new HashSet<transaction_master>();
        }
    
        public long customer_id { get; set; }
        public string customer_code { get; set; }
        public string customer_short_name { get; set; }
        public string customer_name { get; set; }
        public Nullable<bool> is_personal { get; set; }
        public Nullable<bool> enabled { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string update_user { get; set; }
    
        public virtual ICollection<transaction_master> transaction_master { get; set; }
    }
}
