//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryEntities : DbContext
    {
        public InventoryEntities()
            : base("name=InventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category_item> category_item { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<transaction_detail> transaction_detail { get; set; }
        public virtual DbSet<transaction_master> transaction_master { get; set; }
        public virtual DbSet<transaction_type> transaction_type { get; set; }
        public virtual DbSet<unit> units { get; set; }
        public virtual DbSet<user_info> user_info { get; set; }
        public virtual DbSet<warehouse> warehouses { get; set; }
    }
}
