//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_master
    {
        public transaction_master()
        {
            this.transaction_detail = new HashSet<transaction_detail>();
        }
    
        public long transaction_master_id { get; set; }
        public string transaction_code { get; set; }
        public long transaction_type_id { get; set; }
        public System.DateTime transaction_date { get; set; }
        public Nullable<long> received_warehouse_id { get; set; }
        public Nullable<long> delivered_warehouse_id { get; set; }
        public string receiver { get; set; }
        public string deliver { get; set; }
        public Nullable<long> customer_id { get; set; }
        public Nullable<long> supplier_id { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<decimal> percent_charges { get; set; }
        public Nullable<decimal> total_charges { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<bool> enabled { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string update_user { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual supplier supplier { get; set; }
        public virtual ICollection<transaction_detail> transaction_detail { get; set; }
        public virtual warehouse delivered_warehouse { get; set; }
        public virtual warehouse received_warehouse { get; set; }
        public virtual transaction_type transaction_type { get; set; }
    }
}
