//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_detail
    {
        public long transaction_detail_id { get; set; }
        public long transaction_master_id { get; set; }
        public long category_item_id { get; set; }
        public long item_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<long> unit_id { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<decimal> percent_charges { get; set; }
        public Nullable<decimal> total_charges { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string update_user { get; set; }
    
        public virtual category_item category_item { get; set; }
        public virtual item item { get; set; }
        public virtual transaction_master transaction_master { get; set; }
        public virtual unit unit { get; set; }
    }
}
