//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unit
    {
        public unit()
        {
            this.category_item = new HashSet<category_item>();
            this.items = new HashSet<item>();
            this.transaction_detail = new HashSet<transaction_detail>();
        }
    
        public long unit_id { get; set; }
        public string unit_code { get; set; }
        public string unit_name { get; set; }
        public Nullable<bool> enabled { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string update_user { get; set; }
    
        public virtual ICollection<category_item> category_item { get; set; }
        public virtual ICollection<item> items { get; set; }
        public virtual ICollection<transaction_detail> transaction_detail { get; set; }
    }
}
