//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse
    {
        public warehouse()
        {
            this.transaction_master = new HashSet<transaction_master>();
            this.transaction_master1 = new HashSet<transaction_master>();
            this.warehouse1 = new HashSet<warehouse>();
        }
    
        public long warehouse_id { get; set; }
        public string warehouse_code { get; set; }
        public string warehouse_name { get; set; }
        public Nullable<long> warehouse_parent_id { get; set; }
        public Nullable<bool> enabled { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string update_user { get; set; }
    
        public virtual ICollection<transaction_master> transaction_master { get; set; }
        public virtual ICollection<transaction_master> transaction_master1 { get; set; }
        public virtual ICollection<warehouse> warehouse1 { get; set; }
        public virtual warehouse warehouse2 { get; set; }
    }
}
